name: cas
displayName: CAS 统一身份认证
description: 接入 Apereo CAS / OIDC 统一身份认证，作为站点第三方登录提供方。
icon: i-ri:graduation-cap-line
main: online.yudream.base.plugin.tarusso.bootstrap.TaruSsoPlugin
version: "${project.version}"
softdepend:
  - yudream-student-info
